/**
 * @fileoverview Scope module exports.
 */

export {
  type SettingsKind,
  type UserScope,
  type UserScopeGlobal,
  type UserScopeGuild,
  type UserScopeUser,
  type UserScopePerGuildUser,
  type UserScopeId,
  type GuildScope,
  type GuildScopeGlobal,
  type GuildScopeGuild,
  type GuildScopeId,
  type AdminScope,
  type AdminScopeAdmin,
  type AdminScopeId,
  type Scope,
  type ScopeForKind,
  type SettingsActor,
  userScopeGlobal,
  userScopeGuild,
  userScopeUser,
  userScopePerGuildUser,
  guildScopeGlobal,
  guildScopeGuild,
  adminScopeAdmin,
  getScopeKind,
  isGlobalScope,
  getGuildIdFromScope,
  getUserIdFromScope,
  scopeToKey,
  actorAdmin,
  actorGuildAdmin,
  actorUser,
  canActorWriteToScope,
  USER_SCOPES_IN_ORDER,
  GUILD_SCOPES_IN_ORDER,
  ADMIN_SCOPES_IN_ORDER,
} from './scopes';

export {
  USER_SCOPE_PRECEDENCE,
  GUILD_SCOPE_PRECEDENCE,
  getScopePrecedence,
  compareScopePrecedence,
  maxPrecedenceScope,
  minPrecedenceScope,
  type EntryPrecedenceInfo,
  compareEntryPrecedence,
  sortEntriesByPrecedence,
  findWinningEntry,
  filterByImportance,
  type ScopeChainContext,
  buildUserScopeChain,
  buildGuildScopeChain,
  buildAdminScopeChain,
  buildScopeChain,
} from './precedence';
