apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zako3.fullname" . }}-taphub-cache
  labels:
    {{- include "zako3.labels" . | nindent 4 }}
spec:
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.taphub.cacheStorageSize }}
