[package]
name = "zako3-ae-proxy"
version = "0.1.0"
edition = "2024"

[lib]
name = "zako3_ae_proxy"
path = "src/lib.rs"

[[bin]]
name = "zako3-ae-proxy"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = "0.8.8"
dotenvy = { workspace = true }
prometheus = "0.14.0"
protofish4 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zako3-states = { workspace = true, features = ["redis"] }
zako3-telemetry = { workspace = true }
