FROM node:22-alpine AS builder
RUN npm install -g pnpm
WORKDIR /app
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY packages/zako3-data/ /app/packages/zako3-data/
COPY web/ ./web/
ARG VITE_API_BASE_URL=/api/v1
ARG VITE_WS_BASE_URL=ws://localhost
ARG VITE_GRAFANA_URL=http://localhost:3000
ARG NEXT_PUBLIC_DISCORD_INVITE=https://google.com
ARG NEXT_PUBLIC_DOCS_URL=https://docs.zako.ac/docs

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm fetch
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile --offline

RUN pnpm --filter @zako-ac/web --filter @zako-ac/landing-page build

FROM nginx:alpine AS runtime
COPY web/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/web/app/dist /usr/share/nginx/html/app
COPY --from=builder /app/web/landing-page/out /usr/share/nginx/html/landing
EXPOSE 80
