FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*
COPY dist/zako3-emoji-matcher /usr/local/bin/zako3-emoji-matcher
CMD ["zako3-emoji-matcher"]
